### ISSUE TITLE
Config server health endpoint always basing itself on 'default' spring profile

### ISSUE THREAD

**Issue by andreasevers** [spring-cloud/spring-cloud-config#106]
The configserver appears with status “DOWN” for me because:
`org.springframework.cloud.config.client.ConfigServerHealthIndicator`
does a locate of the propertySources to verify if the configServer can access its own properties through the REST endpoint.

This locator is basing itself on an environment object, constructed as such:
```
this.env = new AbstractEnvironment() {};
```
Of course this takes only the default profile, so the loc properties are used.

This results in a REST call being made to:
`http://localhost:8888/application/native,dev/master`
Which of course cannot be reached from dev (which is running on a Jboss).

And because of this, the configServer appears to be “DOWN”, while it in fact is functioning perfectly.

The `env` endpoint returns (among other things) this:
```json
profiles": [
    "dev",
    "native"
  ]
```

There doesn't seem to be a way to tell the config server to use the currently active profile.

**Comment by dsyer** [comment]
I'm not quite following the bit where you say "of course". Is the config server running on port 8888 or not? Is the health indicator in a client application ("application") or in the server itself?

**Comment by andreasevers** [comment]
Oh yes this is probably confusing. The loc profile loads the following `bootstrap.yml`:
```yml
server:
  port: 8888
  servletPath: /*
```
This is deployed on the embedded tomcat of Spring boot.

For `dev` we managed to deploy everything on jboss, using the following `bootstrap-dev.yml`:
```yml
server:
  port: 22121
  contextPath: /configuration
```

The health indicator is in the Spring cloud config server, not another microservice being the client of the server.

In the `application.yml` I've only put things that are allowed to be shared across all microservices, as the property-file resolution also takes `application-{profile}.yml` files of the config server:
```yml
# This file is shared by all microservices
server:
  servletPath: /*
```

**Comment by dsyer** [comment]
If the app is the config server, then you don't really want it to be a config client by default (we were discussing at #104 that the default for the server should be `spring.cloud.config.enabled=false`), so then there wouldn't be a health indicator at all. If I were you I'd just add `spring.cloud.config.enabled=false` to your `bootstrap.yml`.

**Comment by dsyer** [comment]
For the case of a client application I think that the "default" profile is fine for testing if the server is up or not. So all in all I think this is a non-issue once we resolve #104.

**Comment by seno5979** [comment]
Are we sure that this issue has already been fixed.

Because currently I still got issue on client healthIndicator, requesting 'default' profile to config server which resulting below :

````
"configServer": {
"status": "UNKNOWN",
"error": "no property sources located"
},
````

**Comment by spencergibb** [comment]
@seno5979 please, please open a new issue.

**Comment by seno5979** [comment]
Okay. Thanks

**Comment by barrygear** [comment]
Hi. In my case I use gitlab as the backend and the configuration projects are all called <something>.git. So I configured the config server to search for projects like : 
`spring.cloud.config.server.git.uri=git@mygitlab.host:configuration/{application}.git`
This works, however the health check fails.
A config server exception is get : 
`
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: git@mygitlab.host:configuration/application.git: GitLab: The project you were looking for could not be found
.`

In order to avoid this I have to either : 

1. turn off failfast - then my health report is Ok. I just get a warning every 15 seconds.
2. create a project in gitlab called 'application' just to satisfy this health query.
The correct information is present in the code ( the ConfigClientProperties defaults has all the correct info), it just gets wiped out when applying the empty default env.

In terms of health, I want app1 to check on app1s health, not /application/default. I presume this kind of default was chosen so that health can work for uninitialized clients?

**Comment by spencergibb** [comment]
@barrygear 
> please, please open a new issue.
