### ISSUE TITLE
Certificate expiration

### ISSUE THREAD

**Issue by the-player777** [spring-cloud/spring-cloud-config#1227]
Hello,

I was wondering was may happend if I encrypted my sensible keys using a certificate (signed by a CA) which is about to expire. My questions are:

will the config-server still be able to decrypt the keys after the expiration of the certificate?
do I have a possibility to replace the certificate without having to re-encrypt all my keys?

Thanks in advance

**Comment by ryanjbaxter** [comment]
I think the correct solution to this problem is to leverage key rotation

http://cloud.spring.io/spring-cloud-static/Greenwich.RC2/single/spring-cloud.html#_using_multiple_keys_and_key_rotation

**Comment by the-player777** [comment]
I'm not quite sure that it'll solves my problem. I mean even with multiple keys, the certificate itself will still expire one day. Or maybe there's a concept here that I misunderstood.

**Comment by ryanjbaxter** [comment]
a keystore contains both certificates and private keys.  We are using the private keys to encrypt the properties so it is the private key that will need to be changed

**Comment by the-player777** [comment]
I agree, but the private key(s) is linked to a specific certificate. So once the certificate will expire, i will have to:
a) generate a new certificate with a new private key
b) re-encrypt all encrypted values using the new private key

Am I right? Or do I have the possibility to avoid point b) ?

**Comment by spencergibb** [comment]
I'm not sure. @dsyer or @rwinch or @jzheaux

**Comment by dsyer** [comment]
When the private key changes you have different cipher texts, so yes, if you change one you have to change the other.

**Comment by jzheaux** [comment]
In the general sense of key rotation, what happens is that each time a piece of data is encrypted, there is some kind of version attached to it so that it's clear which key to use to decrypt. Then, if that key version is outdated, that data can still be decrypted, and then re-encrypted with the latest version of the key. You can see an example of this pattern in the Vault API: https://www.vaultproject.io/api/secret/transit/index.html#encrypt-data

You can use this pattern to ease the transition to a new key.

Having read @ryanjbaxter's reference just now, I'd suppose that some implementation of `TextEncryptorLocator` could perform this kind of negotiation.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
