### ISSUE TITLE
Could not locate configserver via discovery if config server starts later

### ISSUE THREAD

**Issue by akatkar** [spring-cloud/spring-cloud-config#1498]
When Config server started first there is no problem, but when config client started before config server this error prints continuously. I am not sure whether this is expected behavior or not.  

The exception message is that "java.lang.IllegalStateException: No instances found of configserver (nms-config-server)" 
But I can see the config-server on http://localhost:8761/ (Eureka name server)

So if config server must start first, why try again and again to reach it?
or why config server can not be found on discovery when starts later?
   

Spring Boot Version: 2.1.6.RELEASE
spring-cloud.version: Greenwich.SR2

**Comment by ryanjbaxter** [comment]
This situation is addressed in our documentation
https://cloud.spring.io/spring-cloud-static/Greenwich.SR3/single/spring-cloud.html#config-client-retry

The reason why the client does not know about the config server even though it is registered with Eureka is because the client may not have the latest information from the Eureka server.  If you wait  a bit does the client eventually find the server?

Also the latest Greenwich release is SR3, you should consider upgrading.

**Comment by akatkar** [comment]
Thanks for explanations
