### ISSUE TITLE
Health indicator not enabled by default

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-config#1696]
There's a legacy condition on `ConfigClientAutoConfiguration.ConfigServerHealthIndicatorConfiguration` which only applies if there is a bootstrap context. So the health indicator is disabled by default.

**Comment by spencergibb** [comment]
This will be a bit more involved that at first glance. `PropertySourceLocator` gives direct access to the `PropertSources` where `ConfigData` does not. In the `ContextRefresher` scenario in commons that wasn't a problem.

**Comment by spencergibb** [comment]
Also, we regularly tell folks to disable this as they have systems that ping health which in turn pings config server which causes stability problems with config server (usually git related). We've had discussions before about what "health" of config server means since it's not required (except possibly at startup) or if a refresh happens (and during refresh if it isn't available the app should still run).
