### ISSUE TITLE
Overriding remote properties doesn't work

### ISSUE THREAD

**Issue by kis024** [spring-cloud/spring-cloud-config#2022]
**Describe the bug**
According to [documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud.html#overriding-bootstrap-properties) we should be able to override remote properties with local property sources, but it doesn't work.

**Sample**
Here's a [demo project](https://github.com/kis024/Spring-cloud-config-bug).

**Comment by SquirrelGrip** [comment]
You missed the **spring.cloud.config.overrideSystemProperties=false** from the config/applications.properties

**Comment by kis024** [comment]
In my understanding of this statement: _"and spring.cloud.config.overrideSystemProperties=false if only System properties and env vars should override the remote settings, but not the local config files"_ should make it even more restrictive, since only sys props and env vars values will override the remote values, those from local application.config will be ignored.

In my example I'm looking for using values from local application.config/yml

**Comment by SquirrelGrip** [comment]
You are correct...I am facing the same issue and your example is a great starting point for me.

I have created a heap of tests, but I am also reading the documentation without having too many distractions around (working from home with new neighbours and their new baby screams all the time...sleeping now). It looks that the features that you are mentioning are from the previous version and that as of 3.1.0, these features no longer appear.

Initial finding is that PropertySourceBootstrapProperties has its properties set, however the properties are never read during boot. The only place that they are referenced is in PropertySourceBootstrapConfiguration, however this class is never initialised when I believe it should be. I don't know how to force it to be initialised, but it seems that the class is completely ignored.

I will update my finding as I discover the changes, but as it to say the new way is not documented well and part reading code and deciphering the documentation, I believe that the changes are problematic.

**Comment by SquirrelGrip** [comment]
Long story short...add the following to the client application.properties...
**spring.config.use-legacy-processing=true**

Longer Story...
As you can probably gather from the name, this is the legacy way of handling overrides and there is a newer way to do so. However the new way, since spring boot 2.4, is a little more complicated and I am yet to get it working.
The documentation is not clear and there really needs a better example of how to achieve the same. Also I have tested this with profiles overriding and the results become less understandable and I am still trying to figure it out.

In the meantime, adding spring.config.use-legacy-processing=false should suffice, however it might be bebeficial for the author of the latest changes to make it easier for a newbie to get their head around local overrides in the new system.

**Comment by christian-german** [comment]
Since SB 2.4, [it is no longer possible to override external properties sources](https://www.springcloud.io/post/2022-05/springboot-3-0/#external-configuration-always-overrides-the-configuration-inside-the-jar)

> Add the following to the client application.properties...
> spring.config.use-legacy-processing=true
This works with 2.7 but will be removed with 3.0.0 (Next november). I've just checked against the 3.0.0-SNAPSHOT, indeed, it doesn't work anymore.

The [Spring-Cloud documentation](https://cloud.spring.io/spring-cloud-config/reference/html/#property-overrides) raises the spring.cloud.config.server.overrides property. But this is valid for global configuration. e.g. for all applications.
Server's main application.properties => spring.cloud.config.server.overrides.hello=Hello!
Client's application.properties => hello=Hi!

I can't see a way to override a property from a specific app configuration (client1.properties), like it used to be prior to SB 2.4.

**Comment by ryanjbaxter** [comment]
I believe the way you order things in `spring.config.import` will specify the priority order (the last one will win).

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by kis024** [comment]
@ryanjbaxter what can be ordered here? https://github.com/kis024/Spring-cloud-config-bug/blob/master/src/main/resources/application.properties
Please check the demo project linked in the first comment.

**Comment by kis024** [comment]
spring-boot-starter-parent => 2.7.9
spring-cloud-dependencies => 2021.0.6
Same behaviour.

spring-boot-starter-parent => 3.0.4
spring-cloud-dependencies => 2022.0.1
Same behaviour.

update demo project to latest versions.

**Comment by ryanjbaxter** [comment]
For local overrides to work properly you need to use Bootstrap configuration.  If you add `spring-cloud-starter-bootstrap` to the classpath and then set `spring.cloud.config.uri` in bootstrap.properties and remove the `spring.config.import` property it should work as expected.

**Comment by kis024** [comment]
This is an issue report, not a Stack Overflow question.

**Comment by ryanjbaxter** [comment]
I understand, but this is a limitation that is out of our control because Spring Boot is loading the properties when using `spring.config.import`.  This is why I am suggesting an alternate approach

**Comment by ryanjbaxter** [comment]
The other option is to use a profile specific properties file in the client.  If you create `application-overrides.properties` and activate the `overrides` profile properties in that file will override what comes from the server.

Can you point to where in the docs it still references client side overrides?

**Comment by kis024** [comment]
![image](https://user-images.githubusercontent.com/20765263/226646677-f567c044-a311-4518-afb2-3a56146e2ca4.png)

**Comment by ryanjbaxter** [comment]
That documentation is very old its from `Version: Brixton.BUILD-SNAPSHOT`.

I don't see any references to this in our current docs 
https://docs.spring.io/spring-cloud/docs/current/reference/html/
https://docs.spring.io/spring-cloud/docs/2021.0.5/reference/html/

**Comment by ryanjbaxter** [comment]
Those are environment variable and system properties not application properties

**Comment by kis024** [comment]
Old reference needs to be removed and issue closed.

**Comment by ryanjbaxter** [comment]
> Old reference needs to be removed

Can you be specific about which old references need to be removed?

**Comment by ryanjbaxter** [comment]
I am happy to add some documentation around overriding properties in the local client app.

@christian-german I do not think you need to add `spring.config.use-legacy-processing=true` when using boot 2.7.x with `spring-cloud-starter-bootstrap`.  Also as a side not using `spring-cloud-starter-bootstrap` with Boot 3.0.x will also allow this to continue to work.

**Comment by kis024** [comment]
I was thinking of dropping the misleading page https://cloud.spring.io/spring-cloud-static/spring-cloud.html in favor of https://docs.spring.io/spring-cloud/docs/current/reference/html/

**Comment by ryanjbaxter** [comment]
All of our documentation links point to https://docs.spring.io/spring-cloud/docs/current/reference/html/
