### ISSUE TITLE
Cloud config server returns 404 not found if the label consists of #

### ISSUE THREAD

**Issue by primuppa** [spring-cloud/spring-cloud-config#2084]
Spring Cloud Config supported # in label names when using spring-cloud-config-server 2.1.6 version
Once upgraded to 3.0.5, it does not accept # any more and gives 404 Not Found error. 

Identified the reason for this error
EnvironmentController started using normalize method from PathUtils that identifies label/name/profile containing # as invalid location.

All our existing 100s of labels and newly generated labels all have # (servicename#version-6characters of gitcommit). This the format we follow. This is blocking us to upgrade to latest version.

Is there a reason why label containing # is considered invalid? Is there any plan to fix this?

**Comment by ryanjbaxter** [comment]
Can you try `2021.0.2`?

**Comment by primuppa** [comment]
What is the version number I need to use? 3.0.2? Even that uses the PathUtils isInvalidEncodedLocation which considers # as invalid.

**Comment by ryanjbaxter** [comment]
You should be using the spring cloud bom which will pull in the correct version of spring cloud config

**Comment by primuppa** [comment]
My question is not about that... in the newer version of spring-cloud-config # is considered invalid, is there a reason this was added? Is there a plan to fix this so that it is no more considered invalid?

**Comment by ryanjbaxter** [comment]
It makes a difference because the version you are using is no longer supported, so you should try and use the latest release.  We encourage everyone to use the Spring Cloud Bom instead of specifying the versions themselves.  Hence why I am asking you to try with Spring Cloud 2021.0.2.

It looks like the code you are referencing has not changed in quite a bit of time.
https://github.com/spring-cloud/spring-cloud-config/blame/main/spring-cloud-config-server/src/main/java/org/springframework/cloud/config/server/environment/EnvironmentController.java#L131

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
