### ISSUE TITLE
Client not picking up Spring  cloud config

### ISSUE THREAD

**Issue by sks** [spring-cloud/spring-cloud-config#279]
Hi,

This is my first time with spring cloud and was trying to create a POC based on spring cloud config.

The client service (reservation-service) is configured to talk to the configserver hosted at http://configserver.run.aws-usw02-pr.ice.predix.io/reservation-service/cloud as per 
https://github.com/sks/reservation/blob/master/src/main/resources/bootstrap.properties

```
# Configuration server location
spring.application.name=reservation-service
spring.cloud.config.uri=https://configserver.run.aws-usw02-pr.ice.predix.io
```

But somehow hitting http://localhost:8080/message does not give me the ``` Hello Hello World ``` output

Hitting http://configserver.run.aws-usw02-pr.ice.predix.io/reservation-service/cloud though returns me the expected values, 

```
{
"name": "https://github.com/sks/config-repo/reservation-service.properties",
"source": {
"me": "testing",
"message": "Hello World"
}
}
```

hitting http://localhost:8080/env retrieves the configuration from bootstrap.properties appropriately.

```
"applicationConfig: [classpath:/bootstrap.properties]": {
"spring.cloud.config.enabled": "true",
"spring.cloud.config.uri": "https://configserver.run.aws-usw02-pr.ice.predix.io",
"spring.application.name": "reservation-service"
}
```
Am I missing something here ?

--Thanks
Sabith

**Comment by dsyer** [comment]
Your dependencies are messed up. You have the spring-cloud-cpnfig-server in your client app (which is allowed but unusual), but you aren't using its features. I think you meant to be a config client, so the spring-cloud-starter-config-client would be better because it includes to (important) spring-cloud-context dependency. 

It's also not a great idea to mix Spring Boot 1.3 and Spring Cloud Angel (i.e. Config 1.0), but you might get away with it in this case.
