### ISSUE TITLE
Document monitor functionality

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-config#283]
See https://github.com/spencergibb/spencergibb.github.io/blob/source/content/post/config-server-notifications.md for a start.

**Comment by mmoayyed** [comment]
Perhaps a related issue that spring-cloud-config-monitor is not yet properly released. I only see it in milestone mode, and using the milestone with the official releases of other cloud config modules is not possible since there are API/package changes. Task at hand would be to cut an official release for spring-cloud-config-monitor.

**Comment by dsyer** [comment]
It's already in there.
