### ISSUE TITLE
Exception is not logged when pulling

### ISSUE THREAD

**Issue by prademak** [spring-cloud/spring-cloud-config#364]
We are using spring-cloud-config 1.1.0.M3, and currently repeatedly see a warning being logged:
`Could not pull remote for master (current ref=Ref[refs/heads/master=386bfc56eb3b12de6e638db20180aedabcdef]), remote: git@bitbucket.org:company/config.git`

However, since the Exception is not logged it makes it more difficult to find the actual cause of the problem. 

Therefore I would like to propose the following change at JGitEnvironmentRepository, line 220:
```java
catch (Exception e) {
	this.logger.warn("Could not pull remote for " + label + " (current ref=" + ref
			+ "), remote: " + git.getRepository().getConfig().getString("remote",
			"origin", "url"));
}
```
change to:
```java
               catch (Exception e) {
			this.logger.warn("Could not pull remote for " + label + " (current ref=" + ref
					+ "), remote: " + git.getRepository().getConfig().getString("remote",
							"origin", "url"), e);
		}
```

**Comment by skhome** [comment]
I would like to see the error logging being improved as well.

We faced a similar problem which we were not able to track down to it's root cause.
We had an exception being thrown at the place mentioned above and suspected also an exception being thrown in `MultipleJGitEnvironmentRepository#getLocations` but the 
```
catch (Exception e) {
	continue;
}
```
did hide the root cause.

While I totally agree that the config-server should be as resilient as possible and should rather serve requests from a local potentially stale cache then not at all, having more information available to fix the root cause would be helpful.

**Comment by spencergibb** [comment]
@dsyer any objections to the above changes?

**Comment by dsyer** [comment]
I think it would be too noisy to log the whole stack trace because it's not an error. The multi repo service is trying to find a matching repository for the request. It has to try all of them till it finds one that works. Unless I'm missing something this is quite intentional.

**Comment by skhome** [comment]
My problem is not in the way the server handles the situation, but that it does not provide any clues that help me find the root cause.
How do you feel about logging the exception on DEBUG level, so I could then temporary increase the log verbosity when needed.

**Comment by dsyer** [comment]
I don't like the idea of logging the stack trace at all. We could log the fact that there was an exception at DEBUG level. Do you want to propose a change?

**Comment by tjuchniewicz** [comment]
It would be great to log (even in DEBUG without stacktrace) error in `MultipleJGitEnvironmentRepository#getLocations`

```java
catch (Exception e) {
    continue;
}
```

Now the only way for me to find root cause was debugging.
