### ISSUE TITLE
JGitEnvironmentRepository.shouldPull() isClean() check hides dirty local repo bug

### ISSUE THREAD

**Issue by jeffnelson** [spring-cloud/spring-cloud-config#430]
Running config server version 1.0.4.RELEASE, but it appears this applies to most (if not all) versions.

We've been dealing with an issue with config server returning environment data that does not reflect what is actually in git. We went through many theories on why or how config server was going 'stale'.

We finally figured out that one of our chef jobs was deleting files and folders on the servers with the same name as each microservice as part of a cleanup each time chef runs. This, of course, is a problem for config server because the files in its repo match the app name. Many files within the local git repo used by config server were getting deleted, which causes the repo to become 'dirty'. The current impl of the JGitEnvironmentRepository.shouldPull() method returns false whenever the local repo is not clean.

```
	private boolean shouldPull(Git git, Ref ref) throws GitAPIException {
		return git.status().call().isClean() && ref != null && git.getRepository()
				.getConfig().getString("remote", "origin", "url") != null;
	}
```

Is there a good use case for this local repo to ever be dirty? Shouldn't config server just accept whatever comes from the remote (if there is one)? If there is a good use case for this that I am simply not aware of or not thinking of, feel free to close this issue.

We have changed our chef jobs to be less aggressive and more specific in their cleanup. We will also be looking at adding in an extra health check for config server to check for isClean.

Hopefully this helps someone down the road.

**Comment by dsyer** [comment]
This looks like the same problem as #424 (possibly a variant with a different "helpful" OS clean up process). We added some documentation to warn users about this, but I can imagine we could be more circumpect. The dirty check is there so you can modify the config code locally if you want to, and not blow up when we try to fetch from the remote. This is actually the exact opposite of what you need - local changes are caused by an agent outside the control of the config server and you don't want them to take precedence. Oh well, you can't please all of the people...

If you change the base dir to not be in /tmp your clean up agent probably will be more lenient as well.

I'm not sure we need to change anything, but it would be nice to be more robust. What is the symptom of the staleness in your case? Just getting the wrong data back from the config server? Or is there an exception we can catch and change the behaviour?

**Comment by jeffnelson** [comment]
My idea for a change is two-fold.

1. add a 'forcepull' option. Default false. If true, ignore isClean and discard and local changes. Take from remote.
2. add a logger.warn statement that triggers if local repo goes dirty

**Comment by jeffnelson** [comment]
Sorry- to answer your other questions...

The symptom we saw was config server returning data that didn't match what was in the remote git repo. In some cases, it was missing entire files. In hindsight, the sporadic results should have been a better flag of the true cause.

I don't think there's any exception to be caught.

**Comment by dsyer** [comment]
Sounds good. There's probably an optimization where we only force a pull if the repo is dirty.

**Comment by jeffnelson** [comment]
Looks almost exactly like what I was thinking! 👍
