### ISSUE TITLE
Extends Spring Cloud Config for custom descriptor beans

### ISSUE THREAD

**Issue by pdorgambide** [spring-cloud/spring-cloud-config#461]
[Extends Spring Cloud Config for custom descriptor beans](http://stackoverflow.com/questions/38703731/extends-spring-cloud-config-for-custom-descriptor-beans)
I am worked on a project where a set of classes are used as descriptor beans to allow end users to create instances according the rules defined on the descriptors.
I am not an expert on Spring Cloud but think that its architecture could be fit well to solve this kind of scenarios.
The _Bean Descriptors_ are sort set of  instances that dont change a lot and only system administrator can change and stored as XML files could be feasible.
The _Runtime Instances_ created according _Bean Descriptors_ could be linked to the commit version (or label) and can be always modified according the rules defined for its descriptors (Historic consitence*)

I am aware that this is not a common scenario and maybe is not a good option to implement on this project but this issue could be usefull for think about it and make it real in near future. 

*Maybe is not the best expression

**Comment by ryanjbaxter** [comment]
Sounds like something you might be able to build ontop of the config server?  I am going to close this issue since there is nothing really related to the project itself.  If you find enhancements you would like to make or restrictions in the code base that would stop you from implementing this than feel free to open issues against the project.
