### ISSUE TITLE
Spring Cloud Config Server overrides MessageSource in Spring Boot Plugin

### ISSUE THREAD

**Issue by mraible** [spring-cloud/spring-cloud-config#462]
I'm working on Stormpath's Spring Boot Plugin that has a `MessageSource` pre-defined as follows:

```java
@Bean
@ConditionalOnMissingBean(name = "stormpathSpringMessageSource")
public MessageSource stormpathSpringMessageSource() {
    return super.stormpathSpringMessageSource();
}
```

The `stormpathSpringMessageSource()` method:

```java
public MessageSource stormpathSpringMessageSource() {

    //we need the default i18n keys if the user hasn't configured their own:

    MessageSource messageSource = this.messageSource;

    if (messageSource == null || isPlaceholder(messageSource)) {
        messageSource = createI18nPropertiesMessageSource();
    } else {

        //not null, so the user configured their own.  Need to ensure the stormpath keys are resolvable:

        boolean stormpathI18nAlreadyConfigured = false;

        try {
            String value = messageSource.getMessage(I18N_TEST_KEY, null, Locale.ENGLISH);
            Assert.hasText(value, "i18n message key " + I18N_TEST_KEY + " must resolve to a non-empty value.");
            stormpathI18nAlreadyConfigured = true;
        } catch (NoSuchMessageException e) {
            log.debug("Stormpath i18n properties have not been specified during message source configuration.  " +
                "Adding these property values as a fallback. Exception for reference (this and the " +
                "stack trace can safely be ignored): " + e.getMessage(), e);
        }

        if (!stormpathI18nAlreadyConfigured) {

            //we need to 'wrap' the existing message source and ensure it can fall back to our default values.
            //ensure the user-configured message source is first to take precedence:
            messageSource = new CompositeMessageSource(messageSource, createI18nPropertiesMessageSource());
        }
    }

    return messageSource;
}
```

If I have `spring-cloud-config-server` in my `pom.xml` as a dependency, it fails to load the `MessageSource`. If I remove it, it works fine. How can I make sure my `MessageSource` is still loaded when using Spring Cloud Config Server?

As a workaround, I can define a class as follows and it works, but I'd rather users not have to configure anything.

```java
@Configuration
public class MessagesConfig {

    @Bean
    public MessageSource messageSource() {
        ResourceBundleMessageSource src = new ResourceBundleMessageSource();
        src.setBasename("com.stormpath.sdk.servlet.i18n");
        src.setDefaultEncoding("UTF-8");
        return src;
    }
}
```

**Comment by spencergibb** [comment]
Can you define "it fails to load the MessageSource" some more?

**Comment by lhazlewood** [comment]
@spencergibb It turns out this is a problem for any Spring-boot-based application - if any spring boot plugin/starter wishes to contribute to the overall set of i18n properties, it is not really feasible/easy for anyone not deeply familiar with Spring internals.

For example, the Stormpath starter automatically adds login/logout/resetPassword/etc pages common to identity management.  These are all 'i18n-ified', which means our i18n keys need to be resolvable via the 'one and only one' `MessageSource` found in `AbstractApplicationContext`.

Because this expects a single `MessageSource` bean, we had to go through some trickery.  Here is our solution, which is working really nicely in all environments/configurations we've tested:

https://github.com/stormpath/stormpath-sdk-java/blob/dab0daaaa72645c20e6ec4de90dbe2e657e16613/extensions/spring/stormpath-spring/src/main/java/com/stormpath/spring/context/MessageSourceDefinitionPostProcessor.java

In summary, we created a `CompositeMessageSource` bean.  If the user (or SpringBoot's `MessageSourceAutoConfiguration` on behalf of the user) creates a `MessageSource` bean, we swap that definition for the `CompositeMessageSource` bean definition.  This in turn wraps the user's `MessageSource` and ours.  If a key is not found in the first MessageSource, the next is queried, and so son, down the chain.

Ideally this would be built in to Spring (not just Spring Boot) and allow any number of MessageSource beans to be defined (and ordered).

Would you like me to create a pull request to Spring to add this functionality?  If so, any guidance on which codebase/module/package you would like to see it?  Also please let me know which project I should create a GitHub issue so we can track it.  Any thoughts?

**Comment by spencergibb** [comment]
@lhazlewood and @rmorgan I'm confused about how config server creates this situation. `MessageSource` isn't found [in the codebase at all](https://github.com/spring-cloud/spring-cloud-config/search?utf8=%E2%9C%93&q=messagesource). Can you look at `/beans` and see what `MessageSource` beans are defined? How about a sample that reproduces the problem?

**Comment by lhazlewood** [comment]
@spencergibb per my comments above, this isn't specific to Config Server - it's an issue for any Spring Boot-based application.

I don't have a test-app ready, but here's the scenario:

1.  An app developer doesn't define an explicit `messageSource` bean, and they don't define a `messages.properties` file (which means `MessageSourceAutoConfiguration` won't create a `messageSource` bean either).
2.  The app developer drops in a Spring Boot starter that renders views.  This Spring Boot starter *does* provide a message source, named, e.g. `stormpathSpringMessageSource`.  These auto-provided views use thymeleaf i18n syntax, e.g. `<span th:text="#{stormpath.web.forgotPassword.form.title}">|Forgot your password?|</span>`
3.  The above rendered thymeleaf template will not render the i18n message.

The above occurs because thymeleaf (and any other template rendering that leverages Spring i18n) under the hood will cause interaction with a `messageSource` bean, but this bean wasn't defined by the app developer.

However, because the starter supplies one that's relevant for its out-of-the-box views/templates, i18n should 'just work', without any need for the end-user to specify anything.

My [link above](https://github.com/stormpath/stormpath-sdk-java/blob/dab0daaaa72645c20e6ec4de90dbe2e657e16613/extensions/spring/stormpath-spring/src/main/java/com/stormpath/spring/context/MessageSourceDefinitionPostProcessor.java) makes this happen.

Without that code, Spring or Spring Boot are not capable of the described desired behavior.

**Comment by spencergibb** [comment]
OK. Please open an issue in Spring Boot. Feel free to link to this issue.
