### ISSUE TITLE
Default symmetric encryption is malleable

### ISSUE THREAD

**Issue by huanlenguyen** [spring-cloud/spring-cloud-config#611]
There is a problem with Spring Cloud Config's default symmetric encryption.  It does not mac the cipher text, therefore the encryption is malleable.

**Quick example:**

**Step 1**
Encrypt the string "mysecret":
```
curl localhost:8888/encrypt -d mysecret
9ae30bf0c923d9c892698c9be3cd7d65fced2a901a588f5747e6936eedb9462a
```

If I decrypt the above cipher text I get the expected answer.
```
curl localhost:8888/decrypt -d 9ae30bf0c923d9c892698c9be3cd7d65fced2a901a588f5747e6936eedb9462a
mysecret
```

**Step 2**
If I modify the IV, I can manipulate the plain text to something I desire (I would need to know the plain text to pull off the attack).

To perform attack I take the plain text and xor it with the malicious text:
"mysecret" xor "hacksecr" =  0518100e10170606 (in hex)

Then you take that result and xor it with the start of the iv:
0518100e10170606 xor 9ae30bf0c923d9c8 = new start of iv = 9ffb1bfed934dfce

**Step 3**
new cipher text becomes: 
**9ffb1bfed934dfce**92698c9be3cd7d65fced2a901a588f5747e6936eedb9462a

If I decrypt the new cipher text I get the malicious text
```
curl localhost:8888/decrypt -d 9ffb1bfed934dfce92698c9be3cd7d65fced2a901a588f5747e6936eedb9462a
hacksecr
```

Even without knowing the plain text, I can still produce decryptable data, I just wouldn't know what the output would be.  To prevent this, a mac tag needs to be added to the end of the cipher text or use GCM mode.

This could be a potentially serious problem for organisations that are using symmetric keys as a means of access control for protected configurations.

**Comment by dsyer** [comment]
You can enable GCM mode (it isn't the default for backwards compatibility, but it has been available since 1.0.*). Check out the documentation on `encrypt.rsa.strong` (http://cloud.spring.io/spring-cloud-static/Dalston.SR1/#_appendix_compendium_of_configuration_properties, https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/KeyProperties.java#L152).

Also N.B. this is not a feature of Spring Cloud Config (it's in the Commons project).
