### ISSUE TITLE
MultiAppProperties Arrangement

### ISSUE THREAD

**Issue by remo408** [spring-cloud/spring-cloud-config#784]
Team

How can i formulate my configserver configuration to accommodate properties for multipleapplications with different names:

app1:
app1.properties
persistence.properties
persistence-dev.properties

app2:
app2.properties
xyz.properties
xyz-dev.properties

I tried this use:
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          searchpath : {application}

But soemhow when i say :http://localhost:8888/app1 it returns me 404 please advice

**Comment by spencergibb** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by spencergibb** [comment]
The api is `http://localhost:8888/<app>/<profile>`, so in your case `http://localhost:8888/app1/default`.

**Comment by remo408** [comment]
Hi Spencer thanks for your response that helps :)

**Comment by remo408** [comment]
Hi spencer using the url you specified will only fetch app1/app1.properties and application.properties if any right how can i fetch persistence.properties because using 

`http://localhost:8888/persistence/default.`

is taking it to searchpath persistance where my file is under app1 please advice

**Comment by ryanjbaxter** [comment]
I am confused by your example, are `app1` and `app2` directories?

**Comment by remo408** [comment]
yes ryan ,so app1 folder has app1.prop,persistence.prop & persistence-dev.prop
```

app1/
app1.properties
persistence.properties
persistence-dev.properties
```

**Comment by ryanjbaxter** [comment]
This is a little confusing

```
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          searchpath : {application}
```
I am not sure `{application}` can be used in the `searchpath` property, I thought it can only be used in the `uri` property.  If I can be than it kind of makes sense what you are seeing because the config server is going to look in the `{application}` directory which in this case is `app1` and then load the properties file for that application, which again is `app1`.

You wont be able to access `persistence.properties` because you configuration is going to set the search path to `persistence`.  To make it work you would have to set `searchpath` to `app1,app2`.
