### ISSUE TITLE
Detect and broadcast environment change events in config server

### ISSUE THREAD

**Issue by joshuawhite929** [spring-cloud/spring-cloud-config#86]
When reading the Spring Cloud Config documentation, it appears that the config server is unaware of applications and or profiles until request time. For a given request, the config server seems to boot up a child spring context and resolve a single view of configuration resources using the application name and profile passed in from the request and then dispose of the child context.

Is there a reason why we don't want config server aware of applications/profiles until request time? When thinking about a situation where spring cloud applications need to be aware of a change in configuration, what part of the system is aware of a change in configuration? What then generates the event that the config has changed? As far as I can tell, this is done manually. As a result, we then need to drive a call to the bus so that it can call /refresh on the other applications to reload their configuration.

Have we considered a model where the config server is application/profile aware? Through polling or some other mechanism, it could then be aware of changes for a given application/profile combination. If this was the case, the config server could generate the event for the bus.

As another approach, how about having the config server set up an ATOM feed for application/profile combinations. Applications could then check this feed periodically for changes, refreshing when necessary. This would remove the need for the bus (at least for configuration). Thoughts?

**Comment by dsyer** [comment]
There are two parts to this (I think), and I don't think "profile awareness" adequately describes either of them. One is polling for changes, instead of reacting to a change event, and the other is generating change events automatically in the config server. If we can agree that those are separate concerns we can split the discussion into 2 issues.

Polling the config server for changes would certainly be an alternative approach to using the bus to propagate changes. I think that polling is inferior, generally, to event-driven data flow, but it's an option we could indeed support. I think even the bus could be configured to do it maybe, using Spring Integration HTTP, instead of AMQP (haven't tried that so YMMV). If you get it working a pull request might be a good idea so we can discuss the details.

Generating change events in the config server might also require polling in the general case, but even with this it would probably be better to go with push notifications for the default, if we implement this feature (e.g. Github or Gitlab would do that out of the box). The data model for the event payload is what is interesting (and maybe that's where the "profile awareness" comes in as a possible feature). You would want to know the keys that changed (as per a standard `EvironmentChangeEvent`) and probably also some way to calculate the audience (e.g. the application names and profiles and labels that would be affected). I can imagine there might well be some responsibility on the client application to filter the events so they can understand if they are applicable.

If you have a proposal for the data model it would be interesting to discuss it.

**Comment by joshuawhite929** [comment]
While I see your point about polling, using ATOM-like event feeds can allow you to avoid the need for a bus (which may/may not be desirable).  This approach is a pattern that the ThoughtWorks team seems to have used with success.

Regardless, my interest is in figuring out a way to generate the change event as this functionality is missing today.  Just to be clear, are you advocating push notifications from the config server, github/gitlab or both?

**Comment by dsyer** [comment]
>  are you advocating push notifications from the config server, github/gitlab or both

Both I guess. In the sense that github already provides them, so that would be the easiest implementation of a push from the config server (put an event on the Bus when github pings you).

**Comment by marcellodesales** [comment]
As discussed on #234, I'm interested in building HTTP Clients for different languages like Node.js with Async push notifications as discussed here. In order to generalize, I think there are 2 things to get done: The notification of new commits from the Git Server to the Cloud Config Server and the propagation of the changes, if any, to the listeners.

Git Server -> Push Notification to Cloud Config Server -> Listeners

I would be interested in implementing something more generic, that allows adding different data sinks for the push notification. If we create an interface for the notifications, that would allow developers to implement their own delivery mechanisms. Generally, the above would be:

* Handle push to Git servers through web hooks.
* Compute the deltas of changes in profiles and, for those that changed, notify listeners the different data sinks registered.
 * Message Queues using AMQP - RabbitMQ
 * Amazon SNS
 * Hub that was discussed above.

Config Server
=====

Add different push notification sinks in order to propagate the notifications received from the configured Git Server (GitHub or GitLab). That could be based on Topics which would map to a different Profile (Config + Environment). That way, the Client API would be subscribed to the given chosen implementation.

Git Server
======

GitHub and GitLab implement different APis. The former implements the pubsubhubbub spec while the latter has its own API.

* GitHub: Simpler integration with the PubSub API
 * Notification Hook: https://developer.github.com/v3/repos/hooks/#pubsubhubbub
 * The Config Server admin would need to have an API token to make API calls.

Subscribing 
-----

When the config server receives a new request for a configuration repository, we could just use the subscribe API https://developer.github.com/v3/repos/hooks/#subscribing.

Propagating Git Updates
-------

1) GitHub sends a https://developer.github.com/v3/activity/events/types/#pushevent
2) Config server Iterate over the commit list https://developer.github.com/v3/repos/commits/#get-a-single-commit and verify which files changed through `commit.files.status`.
3) Considering if the contents have changed, post the changes to the different data sinks. Those are only the sub sets of profiles that were changed in the push notification.

* GitLab: I'm sure someone can figure it out as well.
 * http://doc.gitlab.com/ee/web_hooks/web_hooks.html#push-events


Questions
=====

* Are there people interested in working on this?
* Is there any effort already implemented somewhere?

thanks
Marcello

**Comment by dsyer** [comment]
I was already working on this in a branch actually, but the design is basically as you describe (with some additional support for local files via a file watcher). I think it's probably a lot simpler than you think (the Spring Cloud Bus already has support for refresh events, so all we need to do is convert a webhook call into one of those and publish it), but I haven't distilled it to a form that I'm happy with yet. My plan was to introduce a new module that can be added as an optional jar to a config server.

**Comment by dsyer** [comment]
I think this is superseded by #206
