### ISSUE TITLE
Git backend: deleted "feature" branches not skipped during properties lookup

### ISSUE THREAD

**Issue by vasilievip** [spring-cloud/spring-cloud-config#877]
According to doc:
https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#locating-remote-configuration-resources

its possible to specify on client:
```
spring.cloud.config.label=myfeature,develop
```

This leads to ability to deploy service using feature branch and then merge feature branch to master with removal of feature branch, leaving spring.cloud.config.label pointing to missing branch. 
Local repo on config server still has deleted branch and serves settings from this branch which no longer exists. 
Now, assumption is that deletion of branch is OK and if branch is missing - config server will fallback to master and spring.cloud.config.label can contain missing branch. 

There issue is that branch is deleted only in main git repo and if master branch gets updated, w/o restart of config server - changes are not visible by services which have deleted feature branch in startup options.

**Comment by ryanjbaxter** [comment]
So this sounds like if you are going to start merging and deleting branches you will need to restart the config server?  I think this is something we can just document.

**Comment by vasilievip** [comment]
@ryanjbaxter if you do dozens or hundreds of deployments per day using feature branches, keeping those branches is non practical. Having dozens or hundreds of restarts for config service per day just to flush out stale branches seems not practical as well (from automation point of view either)
I would not say that this is documentation only concern.

**Comment by tdanylchuk** [comment]
As this feature is closed and will be available only in  **2.0.0.M9 milestone** is there any possibility to cherry-pick this feature to 1.4.3 and make release, since we would happy to see this feature on prod w\o using M* version.

PS: I've already cherry-picket it already on my repo and tested in 1.4.3 version, everything seems to be smooth.

**Comment by ryanjbaxter** [comment]
@tdanylchuk IDK if it applies so cleanly.  Looks like there are a number of classes that need to be moved over in order to cherry pick this PR even compile.  The major problem I see is that one of the tests appears to be dependent on a JGit API that is only available in JGit 4.* and that required Java 1.8 which we cant swing in the 1.4.x branch.  Maybe the test can be modified, I will have to dig a bit deeper, unless you already did this in your repo and can make a suggestion.

**Comment by tdanylchuk** [comment]
@ryanjbaxter could you check please https://github.com/spring-cloud/spring-cloud-config/pull/947 ?
